version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products_api_production
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/products_api_production
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails

volumes:
  db_data:
